# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justas Palumickas
email: jpalumickas@gmail.com
author: Justas Palumickas
description: > # this means to ignore newlines until "baseurl:"
  Justas Palumickas (jpalumickas) personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jpalumickas.com" # the base hostname & protocol for your site

usernames:
  facebook:    jpalumickas
  github:      jpalumickas
  google_plus: JustasPalumickas
  instagram:   jpalumickas
  linkedin:    jpalumickas
  twitter:     jpalumickas

google_verification_token: ZBm7rz4tEsDW8pxLimtSfy4qkxtL4gZsgjiug0u4ioY
segment_token: O8sX0i2uOlT0sc28P5tSQ83MGM99zmZA


# Build settings
markdown: kramdown

gems:
  - jekyll-babel

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
